### ISSUE TITLE
1.3 RSP images request

### ISSUE THREAD

**Issue by dfalty** [sol-eng/docker-r-session#20]
I'd like to get some 1.3 session images to start testing the preview builds against. Let me know if I can get set up to do this myself so I don't have to bug anyone. :)

**Comment by koverholt** [comment]
We have CI set up on this repo, so we can follow the [release process](https://github.com/rstudio/docker-r-session-complete#release-process-for-docker-images) to make a new version of the images available on Docker Hub for testing.

The latest RSP preview build is 1.3.820-1, do you want me to kick off the creation of images for that version?

**Comment by dfalty** [comment]
Thanks! We were actually close to promoting 1.3.842-1 as a new preview so let's update to that. 

I saw this job failure. https://travis-ci.org/rstudio/docker-r-session-complete/jobs/652824526?utm_medium=notification&utm_source=github_status
I forgot we are no longer building trusty so we need to switch to xenial. https://github.com/rstudio/rstudio-pro/pull/983

**Comment by dfalty** [comment]
Looks like I don't have access to commit. Do you mind giving me access and I can give it a try? :)

**Comment by koverholt** [comment]
> Do you mind giving me access and I can give it a try?

Added!

I opened a PR [here](https://github.com/rstudio/docker-r-session-complete/pull/21), feel free to work on that PR/branch.

And good to know about the xenial build for the session components. 👍

**Comment by koverholt** [comment]
Closed by #21, and the preview images are up on Docker Hub.

We can repeat this process for any new preview builds. Happy testing! 😄
